  name: Get TVL
  on:
    schedule:
      - cron:  '17 * * * *'
  jobs:
    steps:
    - name: Fetch Data to File
      uses: gautemo/fetch-api-data-action@1.1.0
      with:
        url: 'http://101.34.208.17/data'
        file: 'tvl/data.json'